### ISSUE TITLE
질문있습니다.

### ISSUE THREAD

**Issue by HwnagYoungJun** [BD-fromHELL/fakeGG#10]
안녕하세요. 질문사항이 있습니다.

1. 기존 전적검색 사이트에서 게시물의 요청은 페이지네이션 방법으로 구현되어있습니다. 하지만 코드상으로는 단순히 전체 조회처럼 보입니다. 어떻게 구현 할지 궁금합니다.
2. user 설계를 하고있는것처럼 보입니다. 자체 로그인을 가져가는지 아니면 idp로그인 (카카오, 네이버, 구글 등)을 가져가는지 궁금하고 또한 인증방법또한 궁금합니다.
3. 디비 연결이 안되어 있는것처럼 보입니다. 어떤 디비를 사용할것인지 궁금합니다.

또한 개인적인 생각으로 Post라는 이름은 Article이 낫지 않을까 생각됩니다. HTTP 메서드 이름이랑 햇갈려요..

**Comment by Hwan0518** [comment]
안녕하세요! 질문 주셔서 감사합니다
제 설명이 정확할지는 모르겠지만 답변을 드리자면,


1. Page객체를 그대로 return하는것과 Page를 List로 변환해서 return 해주는 것의 차이인데, 일단은 API명세서에 따라서 List로 해주었습니다. List이지만 request시에 원하는 size와 page를 입력하면 그에 알맞은 페이지의 내용이 반환됩니다. size를 입력하지 않는다면 default = 10이므로 페이지당 10개의 게시물이 보여집니다.
(ex. http://url/posts?size=5&page=1)
추가적으로, Page로 구현하는것과 List로 구현하는것의 장단점을 찾아봤는데 Page를 그대로 사용한다면 페이징 정보를 넘겨줄 수 있다는 장점이 있기에 어떤것으로 구현하는지에 대한 논의가 필요해 보입니다. 따라서 다시 한번 얘기해보고 말씀드리겠습니다!


2. 스프링 시큐리티와 JWT로 자체 로그인을 구현할 예정입니다


3. MySQL로 알고있습니다. 현재는 테스트를 쉽게하기위해 H2를 인메모리 방식으로 사용하고 있습니다.


* Post는 기획자의 의견을 100% 수용한 결과이기 때문에, 기획자의 답변을 기다리겠습니다..

**Comment by Hwan0518** [comment]
오늘 회의결과를 토대로 다시 답변 드리겠습니다

1. Pagenation 방식으로 수정할 예정입니다 ! 
또한 nowPage, startPage, endPage를 함께 return하여서 현재 페이지를 기준으로 이전 4개, 이후 5개로, 총 10개의 페이지 번호를 보여주도록 구현했으면 합니다
2. 자체 로그인 + OAuth를 사용하여 소셜 로그인도 같이 구현할 예정입니다

- Posts 엔티티 이름을 Article로 바꾸기로 결정하였습니다! 이상입니다~

**Comment by HwnagYoungJun** [comment]
1번은 이해하기가 조금 어려운거같아요. 

아래는 op.gg의 요청 url입니다.

> https://talk.op.gg/s/lol/all?sort=popular&page=2


(개발자도구 -> 네트워크 탭을 활성화 한 후 페이지를 변경해보시면 찾아보실수 있습니다.)
위와같이 op.gg는 변수를 한개로 컨트롤하는것처럼 보입니다.
보여줄 게시물의 개수를 고정으로 둔다면 해당방법처럼 할 수 있어도 보입니다.
아니라면 ?page=2&size=20과 같이 할 수 도 있겠네요.
