### ISSUE TITLE
[2023/05/23] 회의록

### ISSUE THREAD

**Issue by Hwan0518** [BD-fromHELL/fakeGG#11]
[동환]
====
#### 논의 사항
- 게시글 리스트를 page로 반환 or List로 반환. 어떤걸 선택할것인가?
- page로 반환한다면 nowPage, startPage, endPage를 계산해서 같이 넘겨주자
- API 명세서에서 게시글 리스트 response를 ArticleResponseDto 로 수정해주길 바람
- db는 배포 전에는 h2를 In-Memory db 형태로 사용하고, 나중에 MySQL을 사용하자

#### 이번주 과제
- 게시글 리스트 수정하기
- 로그인 기능 구현  

  
    
[찬준]
====
#### 논의 사항
- 게시글 리스트는 page로 반환하자
- Posts 엔티티는 Article로 바꿀 계획
- 로그인은 자체 로그인 + OAuth2 소셜 로그인 둘 다를 구현하는걸로. 정확한건 목요일에 논의해보기
- 오늘 논의 사항들은 일단 금요일까지 끝내보는걸로

#### 이번주 과제
- Posts를 Article로 바꾸기
- API 명세서 수정
- User 엔티티 수정

**Comment by cksghkd123** [comment]
추가로 게시글+댓글까지 하겠음
