### ISSUE TITLE
Dto Record

### ISSUE THREAD

**Issue by HwnagYoungJun** [BD-fromHELL/fakeGG#22]
java 17을 사용하는것으로 보입니다.
하지만 단순 dto라면 14부터 추가된 Record를 사용해보는건 어떨까요?
간단하게 사용할 수 있고 불필요한 롬복 라이브러리도 줄일 수 있을것같습니다.

**Comment by cksghkd123** [comment]
6/1 목요일 회의 후 사용해보겠습니다!~
