### ISSUE TITLE
Feign client 적용

### ISSUE THREAD

**Issue by HwnagYoungJun** [BD-fromHELL/fakeGG#23]
웹 클라이언트를 쉽게 적용할 수 있는 Feign Client 라이브러리 추가 및 적용

참고: 
- https://techblog.woowahan.com/2630/
- https://docs.spring.io/spring-cloud-openfeign/docs/current/reference/html/

**Comment by cksghkd123** [comment]
활용해서 수정하기로 결정했습니다~
