### ISSUE TITLE
front 코드

### ISSUE THREAD

**Issue by HwnagYoungJun** [BD-fromHELL/fakeGG#31]
front 페이지의 범위를 정하려고 합니다.
어떤 페이지가 필요한지 말씀부탁드릴께요
op.gg 기준으로 스크린샷 및 커스텀하게 어떻게 가져갈것인지까지 적어주시면 감사 하겠습니다.

@cksghkd123 
작업됬던 내용 커밋

**Comment by cksghkd123** [comment]
리포지토리: https://github.com/BD-fromHELL/fakeGG-front
전적 검색 페이지
1. 전적 20개씩 보여줌 (큐 구분없이)
2. 티어 표시

+ 소환사 아이콘, 아이템 이미지는 https://developer.riotgames.com/docs/lol#data-dragon_items 에서 제공하는 url을 통해서 사용하도록 서버에서 key값만 반환하겠습니다.

![image](https://github.com/BD-fromHELL/fakeGG/assets/59885850/5a3c83d7-3951-49b4-9ebc-89e1973bec1b)

**Comment by HwnagYoungJun** [comment]
해당 페이지에서 쓸 api의 명세 작성부탁드립니다. (간단하게 리턴값만 적어줘도 ok)

**Comment by cksghkd123** [comment]
랭크 정보:
{
	"entryModel":
       {
		"queueType":"string",
                "tier":"string",
                "rank":"string",
                "summonerName":"string",
                "leaguePoints":0,
                "wins":0,
                "losses":0
         }

}

전적 1개 (List로 20개 받을 거임)
{
    "gameType": "MATCHED_GAME",
    "gameCreation": 1686780938086,
    "gameDuration": 2094,
    "gameEndTimestamp": 1686783091426,
    "teams": [
        {
            "teamId": 100,
            "win": false,
            "towerKills": 5,
            "inhibitorKills": 0,
            "baronKills": 1,
            "dragonKills": 4,
            "totalKills": 26,
            "totalGolds": 0
        },
        {
            "teamId": 200,
            "win": true,
            "towerKills": 7,
            "inhibitorKills": 1,
            "baronKills": 2,
            "dragonKills": 1,
            "totalKills": 40,
            "totalGolds": 0
        }
    ],
    "participants": [    ////////////////10명 있음
        {
            "championId": 39,
            "championLevel": 17,
            "summonerName": "달리기선수1",
            "rankTier": "IDIAMOND",
            "summonerLevel": 170,
            "summoner1Id": 4,
            "summoner2Id": 12,
            "rune1": 8000,
            "rune2": 8400,
            "kill": 6,
            "death": 9,
            "assist": 0,
            "kda": 0.6666667,
            "킬관여": 0,
            "피해량": 17114,
            "받은피해량": 38916,
            "제어와드": 2,
            "와드설치": 14,
            "와드제거": 3,
            "cs": 295,
            "분당cs": 8.452722,
            "item0": 6631,
            "item1": 3110,
            "item2": 1037,
            "item3": 3153,
            "item4": 3111,
            "item5": 3091,
            "item6": 3363
        },

   .........................




    ]
}

**Comment by cksghkd123** [comment]
수정
랭크정보 =>
{
    "queueType":"string",
    "tier":"string",
    "rank":"string",
    "summonerName":"string",
    "leaguePoints":0,
    "wins":0,
    "losses":0
}
