### ISSUE TITLE
RiotAPI 요청 횟수 문제

### ISSUE THREAD

**Issue by cksghkd123** [BD-fromHELL/fakeGG#33]
- 요청횟수가 많아 에러가 뜹니다.
![image](https://github.com/BD-fromHELL/fakeGG/assets/59885850/0f834012-40d2-493a-80a6-a3d2a5dfc2cb)

 - 요청횟수를 최소한으로 줄인 코드입니다.

     
        public List<MatchModel> getMatches(String summonerName) {

          System.out.println("전적검색중...");
          SummonerModel summoner = getSummoner(summonerName);
  
          String[] matchIdArray = getMatchIdArray(summoner.getPuuid());
          List<MatchModel> matches = new ArrayList<>();
  
          for (String matchId : matchIdArray) {
              Match matchDto = asiaRiotApiClient.getMatch(matchId, apiKey);
  
              Info infoDto = matchDto.getInfo();
  
  
              List<TeamModel> teams = new ArrayList<>();
              System.out.println(infoDto.getTeams());
  
              for (Team teamDto : infoDto.getTeams()) {
                  Objectives objectives = teamDto.getObjectives();
                  TeamModel team = TeamModel.builder()
                          .teamId(teamDto.getTeamId())
                          .win(teamDto.getWin())
                          .baronKills(objectives.getBaron().getKills())
                          .dragonKills(objectives.getDragon().getKills())
                          .inhibitorKills(objectives.getInhibitor().getKills())
                          .towerKills(objectives.getTower().getKills())
                          .totalGolds(0)
                          .totalKills(objectives.getChampion().getKills())
                          .build();
  
                  teams.add(team);
              }
              System.out.println("Team정보 입력");
              List<ParticipantModel> participants = new ArrayList<>();
  
              for (Participant participantDto : infoDto.getParticipants()) {
                  EntryModel entry = getSummonerRank(participantDto.getSummonerId());
                  String rankTier = entry.getRank()+entry.getTier();
  
                  ParticipantModel participant = ParticipantModel.builder()
                          .summonerName(participantDto.getSummonerName())
                          .summonerLevel(participantDto.getSummonerLevel())
                          .rankTier(rankTier)
                          .summoner1Id(participantDto.getSummoner1Id())
                          .summoner2Id(participantDto.getSummoner2Id())
                          .rune1(participantDto.getPerks().getStyles().get(0).getStyle())
                          .rune2(participantDto.getPerks().getStyles().get(1).getStyle())
                          .kill(participantDto.getKills())
                          .death(participantDto.getDeaths())
                          .assist(participantDto.getAssists())
                          .kda(participantDto.getChallenges().getKda())
                          .championId(participantDto.getChampionId())
                          .championLevel(participantDto.getChampLevel())
                          .item0(participantDto.getItem0())
                          .item1(participantDto.getItem1())
                          .item2(participantDto.getItem2())
                          .item3(participantDto.getItem3())
                          .item4(participantDto.getItem4())
                          .item5(participantDto.getItem5())
                          .item6(participantDto.getItem6())
                          .cs(participantDto.getTotalMinionsKilled() + participantDto.getNeutralMinionsKilled())
                          .피해량(participantDto.getTotalDamageDealtToChampions())
                          .받은피해량(participantDto.getTotalDamageTaken())
                          .분당cs((float) ((participantDto.getTotalMinionsKilled() + participantDto.getNeutralMinionsKilled()) / (infoDto.getGameDuration() / 60.0)))
                          .와드설치(participantDto.getWardsPlaced())
                          .와드제거(participantDto.getWardsKilled())
                          .제어와드(participantDto.getDetectorWardsPlaced())
                          .킬관여(Math.round(participantDto.getChallenges().getKillParticipation()))
                          .build();
                  participants.add(participant);
  
                  participants.add(participant);
              }
  
              System.out.println("참가자들 정보 입력 완료");
  
              MatchModel matchModel = MatchModel.builder().gameType(infoDto.getGameType())
                      .gameCreation(infoDto.getGameCreation())
                      .gameDuration(infoDto.getGameDuration())
                      .gameEndTimestamp(infoDto.getGameEndTimestamp())
                      .teams(teams).participants(participants).build();
  
              matches.add(matchModel);
  
          }
          System.out.println("전적 검색 완료!!");
          return matches;
       }

설명 : 
20개의 match를 불러오고 (1회)
각 match에 대한 정보를 불러옵니다(각 1회, 총 20회)
각 match에 들어있는 participants의 랭크정보를 불러옵니다(각 1회, 소환사 10명 => 10회)
총 1+20*10의 요청이 필요합니다.

랭크정보( ex. GOLD 3 )를 불러오기 위해서는 RiotAPI 의 GET_getLeagueEntriesForSummoner 요청을 해서 얻는 방법밖에 없습니다.
(나머지 정보는 participants에 있기에 괜찮음)
여기서 소환사저보를 캐싱하여 사용하면 해결되는건가요?

++Q. 그리고 랭크정보를 포함한 소환사의 정보정도는 db에 저장해놓는게 어떤가를 생각했는데
만약 db에 저장을 해놓은 정보가 최신 소환사정보가 아닐 때 문제가 있기에 사용하지 않는다는게 맞는 판단일까요?

**Comment by HwnagYoungJun** [comment]
일단 이거는 테스트용 키를 받았기 떄문에 어쩔 수 없는 내용이라고 생각합니다. 정식 키를 받게된다면 해당 요청의 제한은 열릴거라고 생각합니다.(아님말고 ㅎ)
만약 위의 내용이 맞다면 대부분 해결 될꺼라고 생각합니다.
+ db에 저장하지 않는 이유는 구지 저장할 필요가 없기때문입니다. db를 운용한다는건 리스크라고 하기에는 그렇지만 짐을 지는거랑 비슷합니다. 명확한 이유(꼭 저장을 해야하는 이유)가 없다면 가져 갈 필요는 없다고 생각합니다.
질문의 핀트를 잘못잡은거같으면 댓글로 말해주세요.

**Comment by HwnagYoungJun** [comment]
그리고 정확한건 아니지만 각 match에 대한 유저의 정보는 펼치기를 실행했을때 요청되는것으로 보이기도 합니다. 그렇게 된다면 페이지가 로딩될때에는
1. 해당 유저의 랭크정보
2. 해당 유저의 랭크정보 이외의 정보
3. 해당 유저의 20경기
만 요청을 정리하고
각각의 게임을 펼치기를 했을때 요청을 또다시 보내는걸로한다면 처음 페이지가 로딩됬을때의 부하를 줄일 수 있을거같습니다.
