### ISSUE TITLE
kakao 로그인 인가 요청

### ISSUE THREAD

**Issue by cksghkd123** [BD-fromHELL/fakeGG#42]
- 아마도 동환님 oauth 설정할 때 아이디에서 인가 설정을 해야할 겁니다. 부탁드립니다.
![image](https://github.com/BD-fromHELL/fakeGG/assets/59885850/5066e6d4-372b-428e-bb09-601393f33e45)

## 현재 상황
게시판,
![image](https://github.com/BD-fromHELL/fakeGG/assets/59885850/2b0f9ce7-2bb9-4f50-91d5-f3827679cff4)
![image](https://github.com/BD-fromHELL/fakeGG/assets/59885850/7f3d5882-1afa-4335-974e-92b148ff8420)

작성 댓글 작성기능 완료

### 대충한 부분
- 방문자수를 그냥 db에서 수정시킴
- 게시글을 html로 변환시키지 않았음
- 대댓글은 확인되지만 표시하지 않음
- 글, 댓글 삭제기능 넣지 않음
- 로그아웃 시 로그아웃하도록 서버에 요청해야함. => 현재는 그냥 로컬스토리지의 토큰만 삭제함..
- 기타 페이지(게시판, 게시글 페이지등..) 이쁘게 꾸미지 않음...

**Comment by Hwan0518** [comment]
redirect url 등록 완료했습니다
